### PR TITLE
Add the Aragonese translation

### PR DESCRIPTION
**Pull request by InakiBes**
I have only added the Aragonese translation. I would appreciate it being accepted. Thank you for your work.

### CODE REVIEW

**Comment by fitojb** [comment]
We now have an official Aragonese orthography !!!!! It’d be great if you could update your translation to use it :)

**Comment by InakiBes** [comment]
Thank you for your message.

It really is a complicated situation and out of respect for science and research, for now, it should not be changed.

There is currently an open dialogue process that I hope will be resolved to everyone's satisfaction.

**Comment by InakiBes** [comment]
Unfortunately, the problem of the Aragonese orthography remains unresolved and, although a few people (but with a strong presence on social networks and political powers) say that the orthography is official, the Government of Aragon has issued a report denying the alleged officiality. 

It really is very sad that this opportunity to normalize our language has been lost.

You can read the report here: https://lenguasdearagon.org/wp-content/uploads/2023/07/INFORME-TRAS-MESAS-DIALOGO.pdf

**Comment by fitojb** [comment]
I am not interested in what politicians have to say; I am interested in what _linguists_ have to say; and linguists have reached a consensus for a unified, compromise orthography. This is your prerogative.

**Review by danielkummer — APPROVED** [review]

**Pull request merged**
