### PR TITLE
Translate into tr_TR

### PR DESCRIPTION
**Pull request by tayfunoziserikan**
This request is for Turkish translation.

### CODE REVIEW

**Comment by tayfunoziserikan** [comment]
:+1:

**Comment by onurozgurozkan** [comment]
:+1:

**Comment by adililhan** [comment]
:cool:

**Comment by yuxel** [comment]
:8ball:

**Comment by emre** [comment]
:+1:  bravo.

**Comment by halit** [comment]
:100:

**Comment by ismailbaskin** [comment]
:8ball:

**Comment by volkan** [comment]
:+1:

**Comment by o** [comment]
:accept:

**Comment by aligundogdu** [comment]
:+1:

**Pull request merged**
